### ISSUE TITLE
CAN Bus Tutorial Project

### ISSUE THREAD

**Issue by Kameroni33** [umatt-ece/new-members-package#5]
# [NM-5] CAN Bus Tutorial Project
## Description
I'd like to create a simple CAN bus example project for two main reasons:

1. So that current electrical members can become familiar with CAN before implementing it on the actual tractor.
2. So that future new members will have a practical project to re-create.

Essentially, for the sample project, I'd like to have 2 different controllers (and Raspberry Pi Pico and Arduino Nano) with CAN chips communicate with each other. Just a simple blink LED type project will do, just something that can respond to user input in real-time that has physical indications. I'd like for this project to be documented as a "tutorial" and added to the _new-members-package_, something that future students could follow along and re-create themselves.

**Objective:** Demonstrate 2-way controller communication via CAN bus and push buttons / LED circuits.

## Tasks
- [ ] Determine list of materials
- [ ] Get approval from council
- [ ] Purchase components
- [ ] Wiring diagram (Arduino Nano)
- [ ] Wiring diagram (Raspberry Pi Pico)
- [ ] CAN bus harnessing
- [ ] Code (Arduino Nano)
- [ ] Code (Raspberry Pi Pico)
- [ ] Build physical unit(s)
- [ ] Test & demonstration

#### Related
- https://github.com/umatt-ece/electrical-projects/issues/2
- https://github.com/umatt-ece/software-projects/issues/2

## Additional Notes
This project will require physical wiring (push button, LED, and CAN controllers). This can just be done on a breadboard, or if you're feeling ambitious it could printed as a custom PCB for practice.
